export default function helloAPI(req, res) {
  res.status(200).json({
    timestamp: 1641585398438,
    context: {
      external_urls: {
        spotify: "https://open.spotify.com/album/5s3rXL4WPTQgCv5Lujy5YI",
      },
      href: "https://api.spotify.com/v1/albums/5s3rXL4WPTQgCv5Lujy5YI",
      type: "album",
      uri: "spotify:album:5s3rXL4WPTQgCv5Lujy5YI",
    },
    progress_ms: 3165,
    item: {
      album: {
        album_type: "album",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/0PEqo7RkX5wkaYwlT6hINn",
            },
            href: "https://api.spotify.com/v1/artists/0PEqo7RkX5wkaYwlT6hINn",
            id: "0PEqo7RkX5wkaYwlT6hINn",
            name: "*repeat repeat",
            type: "artist",
            uri: "spotify:artist:0PEqo7RkX5wkaYwlT6hINn",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RU",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/5s3rXL4WPTQgCv5Lujy5YI",
        },
        href: "https://api.spotify.com/v1/albums/5s3rXL4WPTQgCv5Lujy5YI",
        id: "5s3rXL4WPTQgCv5Lujy5YI",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b2732ca53d3c03bcbd76ccc7bd8d",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e022ca53d3c03bcbd76ccc7bd8d",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d000048512ca53d3c03bcbd76ccc7bd8d",
            width: 64,
          },
        ],
        name: "Floral Canyon",
        release_date: "2017-09-15",
        release_date_precision: "day",
        total_tracks: 12,
        type: "album",
        uri: "spotify:album:5s3rXL4WPTQgCv5Lujy5YI",
      },
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/0PEqo7RkX5wkaYwlT6hINn",
          },
          href: "https://api.spotify.com/v1/artists/0PEqo7RkX5wkaYwlT6hINn",
          id: "0PEqo7RkX5wkaYwlT6hINn",
          name: "*repeat repeat",
          type: "artist",
          uri: "spotify:artist:0PEqo7RkX5wkaYwlT6hINn",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AG",
        "AL",
        "AM",
        "AO",
        "AR",
        "AT",
        "AU",
        "AZ",
        "BA",
        "BB",
        "BD",
        "BE",
        "BF",
        "BG",
        "BH",
        "BI",
        "BJ",
        "BN",
        "BO",
        "BR",
        "BS",
        "BT",
        "BW",
        "BY",
        "BZ",
        "CA",
        "CD",
        "CG",
        "CH",
        "CI",
        "CL",
        "CM",
        "CO",
        "CR",
        "CV",
        "CY",
        "CZ",
        "DE",
        "DJ",
        "DK",
        "DM",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FJ",
        "FM",
        "FR",
        "GA",
        "GB",
        "GD",
        "GE",
        "GH",
        "GM",
        "GN",
        "GQ",
        "GR",
        "GT",
        "GW",
        "GY",
        "HK",
        "HN",
        "HR",
        "HT",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IQ",
        "IS",
        "IT",
        "JM",
        "JO",
        "JP",
        "KE",
        "KG",
        "KH",
        "KI",
        "KM",
        "KN",
        "KR",
        "KW",
        "KZ",
        "LA",
        "LB",
        "LC",
        "LI",
        "LK",
        "LR",
        "LS",
        "LT",
        "LU",
        "LV",
        "LY",
        "MA",
        "MC",
        "MD",
        "ME",
        "MG",
        "MH",
        "MK",
        "ML",
        "MN",
        "MO",
        "MR",
        "MT",
        "MU",
        "MV",
        "MW",
        "MX",
        "MY",
        "MZ",
        "NA",
        "NE",
        "NG",
        "NI",
        "NL",
        "NO",
        "NP",
        "NR",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PG",
        "PH",
        "PK",
        "PL",
        "PS",
        "PT",
        "PW",
        "PY",
        "QA",
        "RO",
        "RS",
        "RU",
        "RW",
        "SA",
        "SB",
        "SC",
        "SE",
        "SG",
        "SI",
        "SK",
        "SL",
        "SM",
        "SN",
        "SR",
        "ST",
        "SV",
        "SZ",
        "TD",
        "TG",
        "TH",
        "TJ",
        "TL",
        "TN",
        "TO",
        "TR",
        "TT",
        "TV",
        "TW",
        "TZ",
        "UA",
        "UG",
        "US",
        "UY",
        "UZ",
        "VC",
        "VE",
        "VN",
        "VU",
        "WS",
        "XK",
        "ZA",
        "ZM",
        "ZW",
      ],
      disc_number: 1,
      duration_ms: 161537,
      explicit: false,
      external_ids: {
        isrc: "US3R21715204",
      },
      external_urls: {
        spotify: "https://open.spotify.com/track/1LTPWQd96vcnMmM5EV96gA",
      },
      href: "https://api.spotify.com/v1/tracks/1LTPWQd96vcnMmM5EV96gA",
      id: "1LTPWQd96vcnMmM5EV96gA",
      is_local: false,
      name: "Girlfriend",
      popularity: 41,
      preview_url:
        "https://p.scdn.co/mp3-preview/3d4e0713c24674b37a96009c81ed9915b0b0bd72?cid=a4685f61580e488f82bfa817e599bed8",
      track_number: 4,
      type: "track",
      uri: "spotify:track:1LTPWQd96vcnMmM5EV96gA",
    },
    currently_playing_type: "track",
    actions: {
      disallows: {
        pausing: true,
        skipping_prev: true,
      },
    },
    is_playing: false,
  });
}
